"""Insightor Publish — Publish human-confirmed review to GitHub.

Parses a human-edited Markdown review draft, extracts feedback, posts the
updated review to GitHub, saves the result, and updates quality metrics.

Usage:
  python scripts/publish.py <markdown-path>
  python scripts/publish.py <markdown-path> --dry-run
  python scripts/publish.py <markdown-path> --json <path>
  python scripts/publish.py --help

The PR URL is auto-detected from the markdown file (embedded during generation).
"""

import asyncio
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from insightor.feedback.draft_parser import DraftParser
from insightor.feedback.quality_tracker import QualityTracker
from insightor.output.github_comment import GitHubCommentOutput
from insightor.output.json_output import JSONOutput
from insightor.schemas.urf import ReviewResult

_PR_URL_RE = re.compile(r"<!--\s*insightor-pr-url:\s*(https?://\S+)\s*-->")


async def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return

    md_path = args[0]
    dry_run = "--dry-run" in args
    json_path = None

    for i, a in enumerate(args):
        if a == "--json" and i + 1 < len(args):
            json_path = args[i + 1]

    md_file = Path(md_path)
    if not md_file.exists():
        print(f"Error: {md_path} not found", file=sys.stderr)
        sys.exit(1)

    # Auto-detect PR URL from markdown
    md_text = md_file.read_text(encoding="utf-8")
    pr_url = _extract_pr_url_from_md(md_text)

    if not pr_url:
        print(
            "Error: Could not find PR URL in markdown file. "
            "Ensure the file was generated by the Insightor review pipeline.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Step 1: Load original ReviewResult from companion JSON
    original = _load_original_result(md_file, pr_url, json_path)
    if original is None:
        print(
            "Error: Could not find companion JSON review file. "
            "Run the review pipeline first to generate review data.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Step 2: Parse edited markdown and apply feedback
    print(f"Parsing {md_path} ...")
    updated_result, changes = DraftParser.parse(md_path, original)
    print(f"  PR: {pr_url}")
    print(f"  Feedback changes detected: {changes}")

    if changes == 0:
        print("  No feedback changes found. Nothing to publish.")
        return

    # Step 3: Dry-run mode
    if dry_run:
        print("\n--- DRY RUN (no changes posted) ---")
        for f in updated_result.findings:
            if f.feedback and f.feedback.status is not None:
                print(
                    f"  [{f.feedback.status.value:14}] "
                    f"{f.title[:55]}  "
                    f"({f.location.path}:{f.location.range.start.line})"
                )
        print("--- end dry run ---")
        return

    # Step 4: Post updated review to GitHub
    print("Publishing to GitHub ...")
    gh = GitHubCommentOutput(pr_url)
    gh.post(updated_result)
    gh.flush()

    # Step 5: Save updated result back to JSON
    json_out = JSONOutput()
    json_out.post(updated_result)

    # Step 6: Track quality metrics
    tracker = QualityTracker()
    tracker.track(updated_result)
    metrics = tracker.export_metrics()
    if metrics.historical_precision:
        print(f"  Quality metrics updated: {metrics.historical_precision}")

    print(f"  Done. Published {changes} feedback changes.")


def _extract_pr_url_from_md(md_text: str) -> str | None:
    """Extract PR URL from the HTML comment embedded during markdown generation."""
    m = _PR_URL_RE.search(md_text)
    if m:
        return m.group(1).strip()
    return None


def _load_original_result(
    md_file: Path, pr_url: str, explicit_json: str | None = None
) -> ReviewResult | None:
    if explicit_json:
        path = Path(explicit_json)
        if path.exists():
            return ReviewResult.model_validate_json(path.read_text(encoding="utf-8"))
        return None

    pr_num = _extract_pr_number(md_file, pr_url)
    if pr_num is None:
        return None

    reviews_dir = Path(".insightor/reviews")
    if not reviews_dir.exists():
        return None

    candidates = sorted(reviews_dir.glob(f"insightor-review-{pr_num}-*.json"))
    if not candidates:
        return None

    latest = candidates[-1]
    return ReviewResult.model_validate_json(latest.read_text(encoding="utf-8"))


def _extract_pr_number(md_file: Path, pr_url: str) -> str | None:
    m = re.search(r"insightor-review-(\d+)", md_file.name)
    if m:
        return m.group(1)
    parts = pr_url.rstrip("/").split("/")
    if parts and parts[-1].isdigit():
        return parts[-1]
    return None


if __name__ == "__main__":
    asyncio.run(main())
